server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/brother_666/tensquare.git
  rabbitmq:
    host: 118.89.190.240
management:   #暴露触发总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
