server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.190.240:3306/tensquare_user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yourpassword
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 118.89.190.240
    password: licong
  rabbitmq:
    host: 118.89.190.240
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
